name: bench-ec2-all
on:
  workflow_dispatch:
jobs:
  bench-gv2:
    name: Graviton2
    uses: ./.github/workflows/bench_ec2_reusable.yml
    permissions: write-all
    with:
      ec2_instance_type: c6g.medium
      ec2_ami_id: ami-096ea6a12ea24a797
      cflags: -mcpu=cortex-a76
      archflags: -march=armv8.2-a
    secrets: inherit
  bench-gv3:
    name: Graviton3
    uses: ./.github/workflows/bench_ec2_reusable.yml
    with:
      ec2_instance_type: c7g.medium
      ec2_ami_id: ami-096ea6a12ea24a797
      cflags: -mcpu=neoverse-v1
      archflags: -march=armv8.4-a
    secrets: inherit
